"""Initial migration

Revision ID: e6554417d6b8
Revises: 
Create Date: 2025-10-06 11:11:27.438930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6554417d6b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_player_turn', sa.Boolean(), nullable=False),
    sa.Column('board', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('player1_rack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('player2_rack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_human_vs_human', sa.Boolean(), nullable=False),
    sa.Column('human_score', sa.Integer(), nullable=True),
    sa.Column('computer_score', sa.Integer(), nullable=True),
    sa.Column('played_words', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('players')
    # ### end Alembic commands ###
